### ISSUE TITLE
 Issue with frameProcessor - TypeError: Cannot read property 'scanOCR' of undefined

### ISSUE THREAD

**Issue by josumonk** [aarongrider/vision-camera-ocr#1]
I'm trying to use this frame processor, everything works fine, it scans the text, but, when i try to use the text, reanimated asks me to run the code on runOnJS, when i simply type.
`import { runOnJS } from "react-native-reanimated";`
The app crashes with this error.
`TypeError: Cannot read property 'scanOCR' of undefined`

This is the import order on the component:
```
import 'react-native-reanimated';
import { runOnJS } from "react-native-reanimated";
import { scanOCR } from "vision-camera-ocr";
```
Package Json
```
"react": "17.0.2",
"react-native": "0.65.1",
"vision-camera-ocr": "^1.0.0",
"react-native-vision-camera": "^2.12.0",
"react-native-reanimated": "^2.3.0-beta.2",
```

**Comment by aarongrider** [comment]
Hey @josumonk, can you try out the example project and let me know if it works for you? The code there might be helpful in determining if the bug is in the library or your project. https://github.com/aarongrider/vision-camera-ocr/blob/main/example/src/App.tsx

Also, make sure you have applied the babel config correctly:
``` js
[
      'react-native-reanimated/plugin',
      {
        globals: ['__scanOCR'],
      },
    ],
```

**Comment by josumonk** [comment]
I tried the example, and everything works great. I tried copying all package versions over my app too, still failing.
But, it worked when i moved around the animation import import 'react-native-reanimated';
Looks like the entry file changes a little bit when using react-native-navigation.

Thanks for the support.

**Comment by ameerarx** [comment]
The same problem on a new project, how can I solve it?

**Comment by josumonk** [comment]
> The same problem on a new project, how can I solve it?

My problem was the file i was importing the animation library, try importing it on the index or if like my project, you are using wix/navigation, the file were the stacks are created

**Comment by mlcal** [comment]
Please try :
react-native start --reset-cache
then
react-native run-android
