### ISSUE TITLE
Expo ios build fails

### ISSUE THREAD

**Issue by moymat** [aarongrider/vision-camera-ocr#24]
Hi !
I'm having an issue when building an ios version with Expo SDK 48 (managed) and the `eas build` command (no issues with android after patching the gradle version).
The build fails at the "Run fastlane" section with this error :

```
The following build commands failed:
	SwiftEmitModule normal arm64 Emitting\ module\ for\ vision_camera_ocr (in target 'vision-camera-ocr' from project 'Pods')
(1 failure)
Exit status: 65
```

Does someone have an idea on how to fix this ?

**Comment by moymat** [comment]
Nevermind, I just had to remove `"useFrameworks": "static"` in the `app.json` file.

**Comment by FrancoOrtiz** [comment]
i'm having another issue with expo, based on the documentation i need to use useFrameProcessor from react-native-vision-camera but this is a native module, so i should eject expo to use it. Do you have the same problem? Is there a way to do this without ejecting expo?

**Comment by dhcmega** [comment]
> command (no issues with android after patching the gradle version).

Hi, how did you patched the gradle version?

thank you

**Comment by moymat** [comment]
> i'm having another issue with expo, based on the documentation i need to use useFrameProcessor from react-native-vision-camera but this is a native module, so i should eject expo to use it. Do you have the same problem? Is there a way to do this without ejecting expo?

I used Expo development client for this since it doesn't work with Expo Go.

**Comment by moymat** [comment]
> > command (no issues with android after patching the gradle version).
> 
> Hi, how did you patched the gradle version?
> 
> thank you

Hi !

You'll have to update the kotlin version in

> node_modules/react-native-vision-camera/android/gradle.properties

to

> VisionCamera_kotlinVersion=1.6.20

Then run

> npx patch-package react-native-vision-camera
